### ISSUE TITLE
installation on Linux

### ISSUE THREAD

**Issue by Sinasta** [wassimj/Topologic#31]
Could someone help me explaining the installation process for archlinux? is there an AUR package available?

**Comment by Sinasta** [comment]
Topology.ByImportedBREP works perfectly fine on my installation. Atleast with simple geometries.

**Comment by wassimj** [comment]
Great. Yes. Topologic on Blender is only planar geometry
________________________________

**Comment by wassimj** [comment]
It seems this is resolved and there are no comments since November so I am closing this issue. Feel free to re-open if any further issues persist.
