### ISSUE TITLE
Compile failure with pybind11 2.10.0

### ISSUE THREAD

**Issue by brunopostle** [wassimj/Topologic#37]
Transferring this bug report from #34

When trying to compile the Python bindings using pybind11 2.10.0, it fails at this point:
```
/src/Attribute.cppwg.cpp:16:9: error: void value not ignored as it ought to be
   16 |         PYBIND11_OVERLOAD_PURE(
      |         ^~~~~~~~~~~~~~~~~~~~~~
```
2.9.2 is ok

**Comment by brunopostle** [comment]
Good news, the Topologic python bindings now seem to be ok with the latest pybind11 and python. Combinations that build here are:

- python-3.10.8 & pybind11-2.7.1
- python-3.10.8 & pybind11-2.9.2
- python-3.11.0 & pybind11-2.10.1
- python-3.11.1 & pybind11-2.10.1

I built a python 3.11 linux binary and added it to [this archive](https://github.com/brunopostle/Topologic/releases/download/2022-04-27/Topologic_2022-12-10_linux.zip) (we don't need to distribute this binary yet as the current blender 3.4 installers still use python 3.10).

**Comment by wassimj** [comment]
Great. Thank you for testing this. I will try to build for windows.
